SET DEFINE OFF

--Row 1
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (1,'Exotic Liquid','Charlotte Cooper','49 Gilbert St.','Londona','EC1 4SD');
--Row 2
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (2,'New Orleans Cajun Delights','Shelley Burke','P.O. Box 78934','New Orleans','70117');
--Row 3
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (3,'Grandma Kelly''s Homestead','Regina Murphy','707 Oxford Rd.','Ann Arbor','48104');
--Row 4
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (4,'Tokyo Traders','Yoshi Nagase','9-8 Sekimai Musashino-shi','Tokyo','100');
--Row 5
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (5,'Cooperativa de Quesos ''Las Cabras''','Antonio del Valle Saavedra ','Calle del Rosal 4','Oviedo','33007');
--Row 6
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (6,'Mayumi''s','Mayumi Ohno','92 Setsuko Chuo-ku','Osaka','545');
--Row 7
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (7,'Pavlova, Ltd.','Ian Devling','74 Rose St. Moonie Ponds','Melbourne','3058');
--Row 8
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (8,'Specialty Biscuits, Ltd.','Peter Wilson','29 King''s Way','Manchester','M14 GSD');
--Row 9
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (9,'PB Knäckebröd AB','Lars Peterson','Kaloadagatan 13','Göteborg','S-345 67');
--Row 10
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (10,'Refrescos Americanas LTDA','Carlos Diaz','Av. das Americanas 12.890','São Paulo','5442');
--Row 11
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (11,'Heli Süßwaren GmbH & Co. KG','Petra Winkler','Tiergartenstraße 5','Berlin','10785');
--Row 12
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (12,'Plutzer Lebensmittelgroßmärkte AG','Martin Bein','Bogenallee 51','Frankfurt','60439');
--Row 13
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (13,'Nord-Ost-Fisch Handelsgesellschaft mbH','Sven Petersen','Frahmredder 112a','Cuxhaven','27478');
--Row 14
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (14,'Formaggi Fortini s.r.l.','Elio Rossi','Viale Dante, 75','Ravenna','48100');
--Row 15
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (15,'Norske Meierier','Beate Vileid','Hatlevegen 5','Sandvika','1320');
--Row 16
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (16,'Bigfoot Breweries','Cheryl Saylor','3400 - 8th Avenue Suite 210','Bend','97101');
--Row 17
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (17,'Svensk Sjöföda AB','Michael Björn','Brovallavägen 231','Stockholm','S-123 45');
--Row 18
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (18,'Aux joyeux ecclésiastiques','Guylène Nodier','203, Rue des Francs-Bourgeois','Paris','75004');
--Row 19
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (19,'New England Seafood Cannery','Robb Merchant','Order Processing Dept. 2100 Paul Revere Blvd.','Boston','02134');
--Row 20
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (20,'Leka Trading','Chandra Leka','471 Serangoon Loop, Suite #402','Singapore','0512');
--Row 21
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (21,'Lyngbysild','Niels Petersen','Lyngbysild Fiskebakken 10','Lyngby','2800');
--Row 22
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (22,'Zaanse Snoepfabriek','Dirk Luchte','Verkoop Rijnweg 22','Zaandam','9999 ZZ');
--Row 23
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (23,'Karkki Oy','Anne Heikkonen','Valtakatu 12','Lappeenranta','53120');
--Row 24
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (24,'G''day, Mate','Wendy Mackenzie','170 Prince Edward Parade Hunter''s Hill','Sydney','2042');
--Row 25
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (25,'Ma Maison','Jean-Guy Lauzon','2960 Rue St. Laurent','Montréal','H1J 1C3');
--Row 26
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (26,'Pasta Buttini s.r.l.','Giovanni Giudici','Via dei Gelsomini, 153','Salerno','84100');
--Row 27
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (27,'Escargots Nouveaux','Marie Delamare','22, rue H. Voiron','Montceau','71300');
--Row 28
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (28,'Gai pâturage','Eliane Noz','Bat. B 3, rue des Alpes','Annecy','74000');
--Row 29
INSERT INTO SUPPLIERS (SUPPLIERID, SUPPLIERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE) VALUES (29,'Forêts d''érables','Chantal Goulet','148 rue Chasseur','Ste-Hyacinthe','J2S 7S8');

COMMIT;