SET DEFINE OFF

--Row 1
INSERT INTO CATEGORIES (CATEGORYID, CATEGORYNAME, DESCRIPTION) VALUES (1,'Beverages','Soft drinks, coffees, teas, beers, and ales');
--Row 2
INSERT INTO CATEGORIES (CATEGORYID, CATEGORYNAME, DESCRIPTION) VALUES (2,'Condiments','Sweet and savory sauces, relishes, spreads, and seasonings');
--Row 3
INSERT INTO CATEGORIES (CATEGORYID, CATEGORYNAME, DESCRIPTION) VALUES (3,'Confections','Desserts, candies, and sweet breads');
--Row 4
INSERT INTO CATEGORIES (CATEGORYID, CATEGORYNAME, DESCRIPTION) VALUES (4,'Dairy Products','Cheeses');
--Row 5
INSERT INTO CATEGORIES (CATEGORYID, CATEGORYNAME, DESCRIPTION) VALUES (5,'Grains/Cereals','Breads, crackers, pasta, and cereal');
--Row 6
INSERT INTO CATEGORIES (CATEGORYID, CATEGORYNAME, DESCRIPTION) VALUES (6,'Meat/Poultry','Prepared meats');
--Row 7
INSERT INTO CATEGORIES (CATEGORYID, CATEGORYNAME, DESCRIPTION) VALUES (7,'Produce','Dried fruit and bean curd');
--Row 8
INSERT INTO CATEGORIES (CATEGORYID, CATEGORYNAME, DESCRIPTION) VALUES (8,'Seafood','Seaweed and fish');

COMMIT;